doctrine:
    dbal:
        url: "mysql://%env(SUITECRM_DATABASE_USER)%:%env(SUITECRM_DATABASE_PASSWORD)%@%env(SUITECRM_DATABASE_HOST)%:%env(SUITECRM_DATABASE_PORT_NUMBER)%/%env(SUITECRM_DATABASE_NAME)%"
